# For public, HTTPS servers.
version: '3'

services:
  kobocat:
    #  build:
    #  image: kobocat:dev.
    #  volumes:
    #    - :/srv/src/kobocat
    environment:
      - ENKETO_PROTOCOL=http
      #- KC_UWSGI_WORKERS_COUNT=4
      #- KC_UWSGI_CHEAPER_WORKERS_COUNT=2
      - NGINX_PUBLIC_PORT=80
      #- KC_UWSGI_MAX_REQUESTS=1024
      #- KC_UWSGI_CHEAPER_RSS_LIMIT_SOFT=1073741824
      #- KC_UWSGI_HARAKIRI=120
      #- KC_UWSGI_WORKER_RELOAD_MERCY=120
      #- DJANGO_SETTINGS_MODULE=onadata.settings.dev
      #- SKIP_CELERY=True
    networks:
      kobo-be-network:
        aliases:
          - kobocat
          - kobocat.docker.container

  kpi:
    #  build:
    #  image: kpi:dev.
    volumes:
      - ../bahis-kobo/kpi/settings/:/srv/src/kpi/kobo/settings/bahis/
      - ../bahis-kobo/kpi/apps/:/srv/src/kpi/kobo/apps/bahis/
    #    - :/srv/src/kpi
    environment:
      - NGINX_PUBLIC_PORT=80
    #  - KPI_UWSGI_WORKERS_COUNT=4
    #  - KPI_UWSGI_CHEAPER_WORKERS_COUNT=2
    #  - KPI_UWSGI_MAX_REQUESTS=1024
    #  - KPI_UWSGI_CHEAPER_RSS_LIMIT_SOFT=1073741824
    #  - KPI_UWSGI_HARAKIRI=120
    #  - KPI_UWSGI_WORKER_RELOAD_MERCY=120
    #  - SKIP_CELERY=True
    #  - DJANGO_SETTINGS_MODULE=kobo.settings.dev
    #  - SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO,https
    #  - FRONTEND_DEV_MODE=host
    networks:
      kobo-be-network:
        aliases:
          - kpi
          - kpi.docker.container

  nginx:
    environment:
      - NGINX_PUBLIC_PORT=80
    #  - UWSGI_PASS_TIMEOUT=130
    ports:
      - 5000:80
    networks:
      kobo-fe-network:
        aliases:
          - kf.docker.internal
          - kc.docker.internal
          - ee.docker.internal

  enketo_express:
    # `DUMMY_ENV` is only there to avoid extra complex condition to override
    # `enketo_express` section or not. It allows to always this section whatever
    # `USE_EXTRA_HOSTS` and `USE_BACKEND_NETWORK` values are.
    environment:
      - DUMMY_ENV=True
    networks:
      kobo-be-network:
        aliases:
          - enketo_express

networks:
  kobo-be-network:
    name: kobo-docker_kobo-be-network
    external: true
