version: '3.8'
services:
  oidc:
    restart: always
    build:
      context: ../../bahis-oidc/
    volumes:
      - ../../bahis-oidc/:/bahis/oidc/
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - ../../bahis-oidc/:/bahis/oidc/
