version: '3.8'
services:
  oidc:
    restart: always
    build:
      context: ./bahis-oidc/
    volumes:
      - ./bahis-oidc/:/bahis/oidc/
    networks:
      - auth_net
      - serve_net
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - ./bahis-oidc/:/bahis/oidc/
    networks:
      - auth_net
networks:
  auth_net:
    driver: bridge
  serve_net:
    external: true
