version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=dj_test
      - POSTGRES_DB=dj_test
      - POSTGRES_PASSWORD=password
    ports:
      - '53:5432'
    volumes:
      - db-vol:/var/lib/postgresql/data
volumes:
  db-vol:
    driver: local
