version: '3.3'
services:
  pgdb:
    restart: always
    # image: postgis/postgis
    # the following build with postgis for arm
    image: ghcr.io/baosystems/postgis:13-3.2
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db:/var/lib/postgresql/data
    container_name: bahisdb
    hostname:
      pgdb
    ports:
      - 5432:5432
    command: ["postgres", "-c", "log_statement=all", "-c", "log_connections=on"]

  rabbitmq:
    restart: always
    image: rabbitmq:latest

  mongodb:
    container_name: mongodb
    restart: always
    image: mongo:4.4

  bahisweb:
    restart: always
    container_name: bahisweb
    build: ./bahisweb
    volumes:
      - ./bahis-serve/:/src_bahis
    depends_on:
      - pgdb
      - mongodb

  nginx:
    restart: always
    container_name: serve-nginx
    image: nginx:latest
    ports:
      - 83:80
    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - ./bahis-serve/:/src_bahis

volumes:
  db:
    name: deployment_db
    driver: local
