version: '3.7'

services:
  dashdb:
    image: postgis/postgis:15-3.4-alpine
    environment:
      - TZ=Asia/Dhaka
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db:/var/lib/postgresql/data
      - ./pgdb/:/docker-entrypoint-initdb.d/
    container_name: dashdb
    hostname:
      dashdb
    networks:
      - dash_net
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_connections=on" ]

  dashboard:
    build:
      context: ./chameleon-canvas/
    container_name: dashboard
    environment:
      - TZ=Asia/Dhaka
    restart: always
    volumes:
      - ./chameleon-data/output/:/home/app/exported_data
    networks:
      - dash_net

  dashboard-ulo:
    build:
      context: ./chameleon-canvas-ulo/
    container_name: dashboard_ulo
    environment:
      - TZ=Asia/Dhaka
    restart: always
    volumes:
      - ./chameleon-data/output/:/home/app/exported_data
    networks:
      - dash_net

  dash-data:
    build:
      context: ./chameleon-data/
    container_name: dash_data
    environment:
      - TZ=Asia/Dhaka
    restart: always
    volumes:
      - ./chameleon-data/output/:/home/app/output
      - /home/bahis/backups/:/home/app/input
    networks:
      - dash_net

  nginx:
    build: ./nginx
    container_name: canvasx
    environment:
      - TZ=Asia/Dhaka
    restart: always
    ports:
      - 2000:80
      - 2001:81
    networks:
      - dash_net

networks:
  dash_net:
    name: dash_net
    driver: bridge

volumes:
  db:
    driver: local
