server {
    listen 80;
    server_name localhost;

    resolver 127.0.0.11 valid=10s ipv6=off;

    location / {
        set $nexus_upstream "nexus:80";
        proxy_pass http://$nexus_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location /media/ {
        alias /usr/share/nginx/media/;
    }
}