version: '3.7'

services:
  pgdb:
    image: postgis/postgis:15-3.4-alpine
    environment:
      - TZ=Asia/Dhaka
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db:/var/lib/postgresql/data
      - ./pgdb/:/docker-entrypoint-initdb.d/
    container_name: dashdb
    hostname:
      dashdb
    networks:
      - dash_net
    command: ["postgres", "-c", "log_statement=all", "-c", "log_connections=on"]

  dashboard:
    build: 
      context: ./bahis-dash/
    container_name: dashboard
    environment:
      - TZ=Asia/Dhaka
    restart: always
    volumes:
      - ./bahis-data/output/:/home/app/exported_data
    networks:
      - dash_net

  dashboard-ulo:
    build: 
      context: ./bahis-dash-ulo/
    container_name: dashboard-ulo
    environment:
      - TZ=Asia/Dhaka
    restart: always
    volumes:
      - ./bahis-data/output/:/home/app/exported_data
    networks:
      - dash_net

  data:
    build:
      context: ./bahis-data/
    container_name: dash-data
    environment:
      - TZ=Asia/Dhaka
    restart: always
    volumes:
     - ./bahis-data/output/:/home/app/output
     - /home/bahis/backups/:/home/app/input
    networks:
      - dash_net

  nginx:
    build: ./nginx
    container_name: dash-nginx
    environment:
      - TZ=Asia/Dhaka
    restart: always
    ports:
      - 2020:80
      - 2021:81
    networks:
      - dash_net

networks:
  dash_net:
    name: dash_net
    driver: bridge

volumes:
  db:
    driver: local
