version: '3.7'

services:
  pgdb:
    image: postgis/postgis:15-3.4-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db:/var/lib/postgresql/data
      - ./pgdb/:/docker-entrypoint-initdb.d/
    container_name: dashdb
    hostname:
      dashdb
    networks:
      - network
    command: ["postgres", "-c", "log_statement=all", "-c", "log_connections=on"]

  dashboard:
    build: 
      context: ./bahis-dash/
    container_name: dashboard
    restart: always
    volumes:
      - ./bahis-data/output/:/home/app/exported_data
    networks:
      - network

  dashboard-ulo:
    build: 
      context: ./bahis-dash-ulo/
    container_name: dashboard-ulo
    restart: always
    volumes:
      - ./bahis-data/output/:/home/app/exported_data
    networks:
      - network

  data:
    build:
      context: ./bahis-data/
    container_name: dash-data
    restart: always
    volumes:
     - ./bahis-data/output/:/home/app/output
     - /home/bahis/backups/:/home/app/input
    networks:
      - network

  nginx:
    build: ./nginx
    container_name: dash-nginx
    restart: always
    ports:
      - 2020:80
      - 2021:81
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  db:
    driver: local
